services:
    builder:
        image: dev
        user: ${UID:-1000}:${GID:-1000}
        restart: no
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        command: turbo build

    ui:
        image: dev
        user: ${UID:-1000}:${GID:-1000}
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        command: turbo dev --filter=ui
        depends_on:
            builder:
                condition: service_completed_successfully
        healthcheck:
            disable: true

    auth-service:
        image: dev
        user: ${UID:-1000}:${GID:-1000}
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        command: turbo dev --filter=auth-service
        depends_on:
            builder:
                condition: service_completed_successfully

    link-service:
        image: dev
        user: ${UID:-1000}:${GID:-1000}
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        command: turbo dev --filter=link-service
        depends_on:
            builder:
                condition: service_completed_successfully

    click-service:
        image: dev
        user: ${UID:-1000}:${GID:-1000}
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        command: turbo dev --filter=click-service
        depends_on:
            builder:
                condition: service_completed_successfully

    statistic-service:
        image: dev
        user: ${UID:-1000}:${GID:-1000}
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        command: turbo dev --filter=statistic-service
        depends_on:
            builder:
                condition: service_completed_successfully

    demo-service:
        image: dev
        user: ${UID:-1000}:${GID:-1000}
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        command: turbo dev --filter=demo-service
        depends_on:
            builder:
                condition: service_completed_successfully

    pgadmin:
        image: dpage/pgadmin4:8.3
        container_name: link-shortener_pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=password
        volumes:
            - link-shortener_pgadmin-data:/var/lib/pgadmin
        ports:
            - 3000:80

    redis-insight:
        container_name: link-shortener_redis-insight
        image: redislabs/redisinsight:latest
        volumes:
            - link-shortener_redis-insight-data:/db
        ports:
            - 4000:5540

    rabbitmq:
        image: rabbitmq:3.12.13-management-alpine
        ports:
            - 5000:15672

volumes:
    link-shortener_redis-insight-data:
    link-shortener_pgadmin-data:
