services:
    nginx:
        container_name: link-shortener_nginx
        image: nginx:1.25.3-alpine
        restart: always
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - client
            - server

    client:
        container_name: link-shortener_client
        build:
            context: ./client
            args:
                - PUBLIC_URL=/dashboard
        environment:
            - PUBLIC_URL=/dashboard
            - PORT=80
        depends_on:
            - server

    server:
        container_name: link-shortener_server
        build:
            context: ./server
        environment:
            - SERVER_PORT=80
            - SESSION_SECRET
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USERNAME
            - DB_PASSWORD
            - DB_DATABASE
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD
        depends_on:
            - postgres
            - redis

    postgres:
        container_name: link-shortener_postgres
        image: postgres:14.4-alpine
        volumes:
            - link-shortener_postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}

    redis:
        container_name: link-shortener_redis
        image: redis:7.0.2-alpine
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - link-shortener_redis:/data

volumes:
    link-shortener_postgres:
    link-shortener_redis:
