services:
    nginx:
        container_name: link-shortener_nginx
        image: nginx:1.25.3-alpine
        restart: always
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - ui

    rabbitmq:
        container_name: link-shortener_rabbitmq
        image: rabbitmq:3.12.13-alpine
        restart: always
        volumes:
            - link-shortener_rabbitmq-data:/var/lib/rabbitmq
            - link-shortener_rabbitmq-logs:/var/log/rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=${RMQ_USERNAME}
            - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}

    ui:
        container_name: link-shortener_ui
        init: true
        build:
            context: .
            dockerfile: apps/ui/Dockerfile
            args:
                - PUBLIC_URL=/dashboard
                - SERVICE=ui
        environment:
            - PUBLIC_URL=/dashboard
            - PORT=80

    auth-service:
        container_name: link-shortener_auth-service
        init: true
        build:
            dockerfile: Dockerfile.nestjs
            context: .
            args:
                - SERVICE=auth-service
        environment:
            - SERVER_PORT=80
            - JWT_PUBLIC_KEY
            - JWT_PRIVATE_KEY
            - RMQ_HOST=rabbitmq
            - RMQ_PORT=5672
            - RMQ_USERNAME
            - RMQ_PASSWORD
            - DB_HOST=auth-service-postgres
            - DB_PORT=5432
            - DB_USERNAME=${AUTH_SERVICE_DB_USERNAME}
            - DB_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
            - DB_DATABASE=postgres
            - REDIS_HOST=auth-service-redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=${AUTH_SERVICE_REDIS_PASSWORD}
        depends_on:
            - auth-service-postgres
            - auth-service-redis
            - rabbitmq

    auth-service-postgres:
        container_name: link-shortener_auth-service-postgres
        image: postgres:14.4-alpine
        volumes:
            - link-shortener_auth-service-postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${AUTH_SERVICE_DB_USERNAME}
            - POSTGRES_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
            - POSTGRES_DB=postgres

    auth-service-redis:
        container_name: link-shortener_auth-service-redis
        image: redis:7.2.4-alpine
        command: redis-server --requirepass ${AUTH_SERVICE_REDIS_PASSWORD}
        volumes:
            - link-shortener_auth-service-redis:/data

    link-service:
        container_name: link-shortener_link-service
        init: true
        build:
            dockerfile: Dockerfile.nestjs
            context: .
            args:
                - SERVICE=link-service
        environment:
            - SERVER_PORT=80
            - JWT_PUBLIC_KEY
            - RMQ_HOST=rabbitmq
            - RMQ_PORT=5672
            - RMQ_USERNAME
            - RMQ_PASSWORD
            - DB_HOST=auth-service-postgres
            - DB_PORT=5432
            - DB_USERNAME=${LINK_SERVICE_DB_USERNAME}
            - DB_PASSWORD=${LINK_SERVICE_DB_PASSWORD}
            - DB_DATABASE=postgres
        depends_on:
            - link-service-postgres
            - rabbitmq

    link-service-postgres:
        container_name: link-shortener_link-service-postgres
        image: postgres:14.4-alpine
        volumes:
            - link-shortener_link-service-postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${LINK_SERVICE_DB_USERNAME}
            - POSTGRES_PASSWORD=${LINK_SERVICE_DB_PASSWORD}
            - POSTGRES_DB=postgres

    click-service:
        container_name: link-shortener_click-service
        init: true
        build:
            dockerfile: Dockerfile.nestjs
            context: .
            args:
                - SERVICE=click-service
        environment:
            - SERVER_PORT=80
            - RMQ_HOST=rabbitmq
            - RMQ_PORT=5672
            - RMQ_USERNAME
            - RMQ_PASSWORD
            - REDIS_HOST=click-service-redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=${CLICK_SERVICE_REDIS_PASSWORD}
        depends_on:
            - click-service-redis
            - rabbitmq

    click-service-redis:
        container_name: link-shortener_click-service-redis
        image: redis:7.2.4-alpine
        command: redis-server --requirepass ${CLICK_SERVICE_REDIS_PASSWORD}
        volumes:
            - link-shortener_click-service-redis:/data

    statistic-service:
        container_name: link-shortener_statistic-service
        init: true
        build:
            dockerfile: Dockerfile.nestjs
            context: .
            args:
                - SERVICE=statistic-service
        environment:
            - RMQ_HOST=rabbitmq
            - RMQ_PORT=5672
            - RMQ_USERNAME
            - RMQ_PASSWORD
            - DB_HOST=statistic-service-postgres
            - DB_PORT=5432
            - DB_USERNAME=${STATISTIC_SERVICE_DB_USERNAME}
            - DB_PASSWORD=${STATISTIC_SERVICE_DB_PASSWORD}
            - DB_DATABASE=postgres
        depends_on:
            - statistic-service-postgres
            - rabbitmq

    statistic-service-postgres:
        container_name: link-shortener_statistic-service-postgres
        image: postgres:14.4-alpine
        volumes:
            - link-shortener_statistic-service-postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${STATISTIC_SERVICE_DB_USERNAME}
            - POSTGRES_PASSWORD=${STATISTIC_SERVICE_DB_PASSWORD}
            - POSTGRES_DB=postgres

volumes:
    link-shortener_auth-service-postgres:
    link-shortener_auth-service-redis:
    link-shortener_link-service-postgres:
    link-shortener_rabbitmq-data:
    link-shortener_rabbitmq-logs:
    link-shortener_click-service-redis:
    link-shortener_statistic-service-postgres:
