services:
    rabbitmq:
        image: rabbitmq:3.12.13-management-alpine
        ports:
            - 15672:15672

    ui:
        image: dev
        user: ${UID:-1000}:${GID:-1000}
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        command: turbo dev --filter=ui

    auth-service:
        image: dev
        user: ${UID:-1000}:${GID:-1000}
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        command: turbo dev --filter=auth-service
        ports:
            - 4000:80

    link-service:
        image: dev
        user: ${UID:-1000}:${GID:-1000}
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        command: turbo dev --filter=link-service
        ports:
            - 4100:80

    redis-insight:
        container_name: link-shortener_redis-insight
        image: redislabs/redisinsight:latest
        volumes:
            - link-shortener_redis-insight-data:/db
        ports:
            - 5000:5540

    pgadmin:
        image: dpage/pgadmin4:8.3
        container_name: link-shortener_pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=password
        volumes:
            - link-shortener_pgadmin-data:/var/lib/pgadmin
        ports:
            - 4200:80

volumes:
    link-shortener_redis-insight-data:
    link-shortener_pgadmin-data:
