FROM node:20.10.0-alpine

ENV NODE_ENV=development

WORKDIR /app

# Tools
RUN apk add git

RUN apk add curl

RUN apk add bash

RUN npm i -g turbo@^1.13.4

# Aliases
RUN echo 'alias ll="ls -lAhS"' >> ~/.bashrc

CMD sleep 1d
