services:
    server:
        container_name: link-shortener_server
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            - SERVER_PORT=4200
        ports:
            - 4200:4200
