services:
    client:
        build:
            dockerfile: Dockerfile.dev
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
    server:
        build:
            dockerfile: Dockerfile.dev
        volumes:
            - ./server:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
