services:
    client:
        build:
            dockerfile: Dockerfile.dev
        volumes:
            - ./client:/app
            - /app/node_modules

    server:
        build:
            dockerfile: Dockerfile.dev
        volumes:
            - ./server:/app
            - /app/node_modules
