/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type RegisterDTO = {
	/**
	 * @minLength 4
	 * @maxLength 32
	 */
	username: string
	/**
	 * @minLength 8
	 * @maxLength 32
	 */
	password: string
}

export type User = {
	username: string
	id: number
	/**
	 * @format date-time
	 */
	createdAt: string
	/**
	 * @format date-time
	 */
	updatedAt: string
}

export type LoginDTO = {
	username: string
	password: string
}

export type UsernameCheckDTO = {
	isTaken: boolean
}

export type CreateLinkDTO = {
	/**
	 * Url with protocol, host and tld.
	 *
	 * @example https://google.com
	 */
	destination: string
	/**
	 * @minLength 1
	 * @maxLength 32
	 */
	name: string
}

export type Link = {
	backhalf: string
	name: string
	destination: string
	id: number
	/**
	 * @format date-time
	 */
	createdAt: string
	/**
	 * @format date-time
	 */
	updatedAt: string
}

export type UpdateLinkDTO = {
	/**
	 * Url with protocol, host and tld.
	 *
	 * @example https://google.com
	 */
	destination?: string
	/**
	 * @minLength 1
	 * @maxLength 32
	 */
	name?: string
}

export type LinkStatisticDTO = {
	platforms: {
		[key: string]: number
	}
	browsers: {
		[key: string]: number
	}
	systems: {
		[key: string]: number
	}
	devices: {
		[key: string]: number
	}
	clicks: number
}
