name: statistic-service
namespace: link-shortener
replicas: 4

container:
  image: <IMAGE_REPOSITORY_URL>
  env:
    - name: RMQ_HOST
      valueFrom:
        configMapKeyRef:
          name: rabbitmq
          key: host
    - name: RMQ_PORT
      valueFrom:
        configMapKeyRef:
          name: rabbitmq
          key: port
    - name: RMQ_USERNAME
      valueFrom:
        secretKeyRef:
          name: rabbitmq
          key: username
    - name: RMQ_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rabbitmq
          key: password
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: postgres
          key: host
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: postgres
          key: port
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: postgres
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres
          key: password

configMap:
  data:
    DB_DATABASE: statistic-service
